@startuml
  !include 01-macros.pu

  FAM_BEGIN(Емельяновы)
    node(ix, Емельянов Николай Николаевич, Емельянова Валентина Степановна)
    child(ix, Емельянова Светлана Николаевна, Емельянова Марина Николаевна)

    node(ix.2, Федулов Станислав, Емельянова Марина Николаевна)
  FAM_END

  FAM_BEGIN(Поляковы)
    node(ix.1, Поляков Сергей, Емельянова Марина Николаевна)
    child(ix.1, Поляков Алексей Сергеевич)
  FAM_END
@enduml
