@startuml
  !include 01-macros.pu

  FAM_BEGIN(Зельдичи)
    nodeM(ix.0, Алимов Бедретдин)
    child(ix.0, Алимов Сафа Бедретдинович, Алимов Абдурахман Бедретдинович)

    node(ix.1, Алимов Абдурахман Бедретдинович, Боброва Хадича)
    child(ix.1, Алимова Суфия Абдурахмановна)

    node(ix.2, Зельдич Анатолий Наумович, Алимова Суфия Абдурахмановна)
    child(ix.2, Зельдич Эдуард Анатольевич, Алимова Эльмира Анатольевна)

    node(ix.3, Зельдич Эдуард Анатольевич, Кашина Татьяна Сергеевна)
    child(ix.3, Зельдич Юлия Эдуардовна, Зельдич Тимур Эдуардович)

    node(ix.4, Зельдич Тимур Эдуардович, ? Александра Павловна)
    child(ix.4, Зельдич Артём Тимурович, Зельдич Варвара Тимуровна)
  FAM_END
@enduml
