@startuml
  !include 01-macros.pu

  FAM_BEGIN(Култашевы)
    node(ix.дв.сестра.б.нины, Моляков, Култашева Нина Александровна)

    nodeM(ix.родители.б.ани, Култашев Иван)
    child(ix.родители.б.ани, Култашева Анна Ивановна, Култашев Александр Иванович)
    child(ix.родители.б.ани, Култашев Петр Иванович, брат 3, Култашева Татьяна Ивановна)

    nodeM(ix.дядя.б.нины, Култашев Александр Иванович)
    child(ix.дядя.б.нины, Култашева Нина Александровна)

    node(ix.дядя.б.нины.петр, Култашев Петр Иванович, Култашева Агриппина Александровна)
    child(ix.дядя.б.нины.петр, Култашева Елизавета Петровна, Култашева Анна Петровна)

    node(ix.б.аня, Василий, Култашева Анна Ивановна)
    child(ix.б.аня, Култашева Нина Васильевна)

    node(ix.1, Широков Борис Аркадьевич, Култашева Нина Васильевна)
    child(ix.1, Култашев Николай Борисович)

    node(ix.2, Иванов Николай, Култашева Нина Васильевна)
    child(ix.2, Иванова Наталья Николаевна)

    node(ix.3, Култашев Николай Борисович, Кашина Наталья Сергеевна)
    child(ix.3, Култашев Николай Николаевич, Култашев Александр Николаевич)
    info(Култашев Николай Николаевич, DATE(1972, 03, 10), BORN(Москва))

    node(ix.4, Култашев Николай Николаевич, Емельянова Светлана Николаевна)
    child(ix.4, Култашева Алёна Николевна)

    node(ix.5, Култашев Николай Николаевич, Спирова Александра Васильевна)
    child(ix.5, Култашев Андрей Николаевич, Култашев Антон Николаевич)

    node(ix.6, Култашев Александр Николаевич, Березницкая Ирина)
    child(ix.6, Култашев Альберт Александрович, Култашева Арина Александровна)
  FAM_END

  FAM_BEGIN(Степановы)
    node(ix.тетя.б.нины, Степанов Матвей, Култашева Татьяна Ивановна)
    child(ix.тетя.б.нины, Степанов Павел Матвеевич, Степанова Мария Матвеевна)
  FAM_END

  FAM_BEGIN(Лебедевы)
    node(ix.лебедев, Лебедев Валерий, Иванова Наталья Николаевна)
    child(ix.лебедев, Лебедева Анна Валерьевна)

    node(ix.аня, Карпов Сергей Олегович, Лебедева Анна Валерьевна)
    child(ix.аня, Лебедев Олег Сергеевич)
  FAM_END

  FAM_BEGIN(Тищенко)
    node(ix.тищенко, Тищенко Павел, Иванова Наталья Николаевна)
    child(ix.тищенко, Тищенко Александр Павлович)
  FAM_END

@enduml
