@startuml
  !include 01-macros.pu

  FAM_BEGIN(Зельдичи)
    node(ix, Зельдич Эдуард Анатольевич, Кашина Татьяна Сергеевна)
    child(ix, Зельдич Юлия Эдуардовна, Зельдич Тимур Эдуардович)

    node(ix.1, Зельдич Тимур Эдуардович, Зельдич Александра)
    child(ix.1, Зельдич Артём Тимурович, Зельдич Варвара Тимуровна)
  FAM_END
@enduml
