@startuml
  !include 01-macros.pu

  FAM_BEGIN(Боталовы)
    nodeM(ix.родители.бабушки, Боталов Яков)
    child(ix.родители.бабушки, Боталова Марфа Яковлевна, Боталова Татьяна Яковлевна)
  FAM_END

  FAM_BEGIN(Балабановы)
    node(ix.бабушка.татьяна, Балабанов ? ?, Боталова Татьяна Яковлевна)
    child(ix.бабушка.татьяна, Балабанов Александр, Балабанова Ирина, Балабанова Валентина)
  FAM_END

  FAM_BEGIN(Голубевы)
    node(ix.дед.по.матери, Голубев Иван, Гржибовская Пелагея)
    child(ix.дед.по.матери, Голубева Анна Ивановна, Голубева Полина Ивановна)
  FAM_END

  FAM_BEGIN(Кондратьевы)
    nodeM(ix.кондратьев, Кондратьев)
    child(ix.кондратьев, Кондратьев Виктор, Кондратьев Лев, Кондратьев Илья)

    node(ix.тетя.полина, Кондратьев Илья, Голубева Полина Ивановна)
    child(ix.тетя.полина, Кондратьев Геннадий Ильич, Криволапова Людмила Ильинична)
  FAM_END

  FAM_BEGIN(Макаровы)
    node(ix.валентина.макарова, Макаров, Балабанова Валентина)
  FAM_END

  FAM_BEGIN(Кашины)
    nodeM(ix.прадед, Кашин Яков)
    child(ix.прадед, Кашин Ефим Яковлевич)

    node(ix.дед, Кашин Ефим Яковлевич, Боталова Марфа Яковлевна)
    child(ix.дед, Кашин Павел Ефимович, Кашин Василий Ефимович, Кашин Яков Ефимович, Кашин Вениамин Ефимович)
    child(ix.дед, Кашина Татьяна Ефимовна, Кашина Мария Ефимовна, Кашина Наталья Ефимовна)

    nodeM(ix.дядя.яков, Кашин Яков Ефимович)
    child(ix.дядя.яков, Кашин Александр Яковлевич, Кашин ? Яковлевич)

    node(ix.отец.1, Кашин Василий Ефимович, Голубева Анна Ивановна)
    child(ix.отец.1, Кашин Сергей Васильевич)

    nodeF(ix.тетя.наталья, Кашина Наталья Ефимовна)
    child(ix.тетя.наталья, Зоя, Александр)

    node(ix.отец.2, Кашин Василий Ефимович, Мусорина Клавдия Алексеевна)
    child(ix.отец.2, Кашин Юрий Васильевич)

    node(ix.отец.3, Кашин Василий Ефимович, Кудрина Феофанья)

    node(ix.1, Кашин Сергей Васильевич, Панкова Клара Ивановна)
    child(ix.1, Кашина Татьяна Сергеевна, Кашина Наталья Сергеевна)

    node(ix.2, Кашин Сергей Васильевич, Шельверчук Валентина Сергеевна)
    child(ix.2, Кашина Елена Сергеевна)
  FAM_END

  FAM_BEGIN(Дерябины)
    node(ix.тетя.мария, Дерябин Михаил ?, Кашина Мария Ефимовна)
    child(ix.тетя.мария, Дерябина Надежда Михайловна, Дерябина (Кузнецова) Нина Михайловна)
  FAM_END
@enduml
