@startuml
  !include 01-macros.pu

  FAM_BEGIN(Генераловы)
    nodeM(ix.прапрадед.2, ? Захар)
    child(ix.прапрадед.2, ? Наталья Захаровна)

    node(ix.прадед.3, Генералов Василий, ? Наталья Захаровна)
    child(ix.прадед.3, Генералова Мария Васильевна, Генералова Зоя Васильевна)
    info(Генералова Мария Васильевна, DATE(1922, 11, 27, 1999, 12, 29), Южный)
    info(Генералова Зоя Васильевна, DATE(?, 05, ?, 1996, 03, 09), Барыбино)
  FAM_END

  FAM_BEGIN(Сарваровы)
    nodeM(ix.прапрадед.1, Сарваров Василий)
    child(ix.прапрадед.1, Сарварова Александра Васильевна)
    info(Сарварова Александра Васильевна, YEARS(1900, ?), Барыбино)
  FAM_END

  FAM_BEGIN(Пирожковы)
    nodeM(ix.прадед.2, Пирожков Павел)
    child(ix.прадед.2, Пирожкова Галина Павловна)
    info(Пирожкова Галина Павловна, DATE(1941, 03, 08, ?), Барыбино)
  FAM_END

  FAM_BEGIN(Поспеловы)
    node(ix.прадед.1, Поспелов Фёдор, Сарварова Александра Васильевна)
    child(ix.прадед.1, Поспелов Сергей Фёдорович)
    info(Поспелов Сергей Фёдорович, DATE(?, 03, 15, ?), Барыбино)

    node(ix.дед.1, Поспелов Сергей Фёдорович, Пирожкова Галина Павловна)
    child(ix.дед.1, Поспелов Вячеслав Сергеевич, Поспелова Светлана Сергеевна)
    info(Поспелов Вячеслав Сергеевич, ЦОС ВИУА)
    info(Поспелова Светлана Сергеевна, DATE(1961, 01, 06, 2014, 05, 21), Южный)

    node(ix.дядя, Поспелов Вячеслав Сергеевич, Поспелова Ольга)
    child(ix.дядя, Поспелова Юлия Вячеславовна)
    info(Поспелова Ольга, ЦОС ВИУА)
    info(Поспелова Юлия Вячеславовна, ЦОС ВИУА)

    node(ix.дв.сестра, Поспелова Юлия Вячеславовна, ? Александр)
    child(ix.дв.сестра, Поспелов Арсений Сергеевич)
  FAM_END

  FAM_BEGIN(Спировы)
    node(ix.дед.2, Спиров Юрий Васильевич, Генералова Зоя Васильевна)
    child(ix.дед.2, Спиров Василий Юрьевич)
    info(Спиров Юрий Васильевич, DATE(1926, 07, 29, 1996, 06, 24), Барыбино)
    info(Спиров Василий Юрьевич, DATE(1962, 06, 03), Южный)

    node(ix, Спиров Василий Юрьевич, Поспелова Светлана Сергеевна)
    child(ix, Спирова Александра Васильевна)
    info(Спирова Александра Васильевна, DATE(1981, 12, 13), Москва)
  FAM_END
@enduml
