@startuml
  !include 01-macros.pu

  FAM_BEGIN(Шахматовы)
    node(ix.1, Шахматов Яков Егорович, Бурундукова Евдокия Матвеевна)
    child(ix.1, Шахматов Михаил Яковлевич, Шахматов Владимир Яковлевич, Шахматова Александра Яковлевна)

    node(ix.11, Шахматов Михаил Яковлевич, Анна Трофимовна)
    child(ix.11, Шахматова Тамара Михайловна)

    node(ix.12, Шахматов Владимир Яковлевич, Мария)
    child(ix.12, Шахматов Николай Владимирович, Шахматова Галина Владимировна)
    child(ix.12, Шахматов Борис Владимирович, Шахматов Сергей Владимирович, Шахматова Лидия Владимировна)
  FAM_END

  FAM_BEGIN(Галюковы)
    node(ix.111, Галюков Валентин, Шахматова Тамара Михайловна)
    child(ix.111, Галюкова Людмила Валентиновна,  Галюкова Ираида Валентиновна, Галюкова Наталья Валентиновна)
  FAM_END

  FAM_BEGIN(Андреевы)  
      node(ix.1113, Андреев Геннадий, Галюкова Наталья Валентиновна)
      child(ix.1113, Андреев Михаил Геннадиевич, Андреев Андрей Геннадиевич)
  FAM_END

  FAM_BEGIN(Четвалинские)
    node(ix.1111, Четвалинский Вячеслав, Галюкова Людмила Валентиновна)
    child(ix.1111, Четвалинский Аркадий Вячеславович, Четвалинская Наталья Вячеславовна)
  FAM_END

  FAM_BEGIN(Леонтьевы)
      node(ix.1112, Леонтьев Юрий, Галюкова Ираида Валентиновна)
      child(ix.1112, Леонтьев Андрей Юрьевич, Леонтьев Александр Юрьевич)
  FAM_END

  FAM_BEGIN(Панковы)
      node(ix.13, Панков Иван Федосеевич, Шахматова Александра Яковлевна)
      child(ix.13, Панкова Клара Ивановна)
  FAM_END
@enduml
